FROM alpine:3.6

RUN apk update

RUN apk add --no-cache \
    build-base \
    gcc \
    g++ \
    make \
    cmake \
    gdb \
    libstdc++ \
    libevent \
    libevent-dev \
    libexecinfo-dev \
    bsd-compat-headers \
    linux-headers 
    
